config/routes.rb
Rails.application.routes.draw do
  resources :maquillajes
  resources :comments, except: %i[index new show]
  resources :categories
  resources :profiles

  get '/maquillajes', to: 'maquillajes#index'

  get '/confirm_email/:token', to: 'users#confirm_email'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  delete '/user/:id', to: 'users#destroy', as: 'user_destroy'

  post '/login', to: 'sessions#create', as: 'create_session'
  get '/login', to: 'sessions#login', as: 'login'

  get '/user/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/user/:id', to: 'users#update', as: 'update_user'
  get '/user/:id', to: 'users#show', as: 'user'
  get '/users', to: 'users#index'
  
  get '/signup', to: 'users#new', as: 'signup'
  post '/users', to: 'users#create', as: 'create_user'


  patch '/articles/:id', to: 'articles#update', as: 'update_article'
  post '/articles', to: 'articles#create'
  delete '/articles/:id', to: 'articles#destroy', as: 'article_destroy'
  get '/articles', to: 'articles#index'
  get '/articles/new', to: 'articles#new'
  get '/articles/:id', to: 'articles#show', as: 'article'
  get '/articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "pages#home"
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_token :token, length: 50
    validates :email, presence: true
    validates :password, presence: true, length: { minimum: 6 }, if: :password_present?
    validates :password_confirmation, length: { minimum: 6 }, if: :password_present?
    has_secure_password # This adds methods to set and authenticate against a BCrypt password.
    has_many :articles, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_one :profile, dependent: :destroy

    private

    def password_present?
        false || password.present?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authenticate_user!, only: [:new, :create, :confirm_email]
    before_action :set_user, only: %i[show edit update destroy] 
    
    def index
        @users = User.all
        # Fetch all users to display in the index view
    end

    def show
    end
    
    def new
        @user = User.new
        # Initialize a new user object for the signup form
    end

    def edit
        # This action is used to render the edit user form
        # The @user instance variable is set by the before_action :set_user
    end

    def update
        if @user.update(user_params)
            redirect_to user_path(@user), notice: "User was successfully updated."
            # Redirect to the user's show page after successful update
        else
            render :edit, status: :unprocessable_entity
            # Render the edit template if validation fails
        end
    end

    def destroy
    
        session[:user_id] = nil if current_user == @user
        @user.destroy
        redirect_to users_path, notice: "User was successfully deleted."
        # Redirect to the users index page after successful deletion
    end

    def confirm_email
        user = User.find_by(token: params[:token])
        user.update!(is_confirmed?: true)
        redirect_to login_path, notice: "Your email has been confirmed. Please log in."
    end

    # This action handles user signup
    # It creates a new user and logs them in if successful


    def create
        @user = User.new(user_params)
        if @user.save
            UserMailer.with(user: @user).confirm_account.deliver_later
            redirect_to login_path, notice: "An email was sent to your account to confirm your email address."
            # Redirect to the articles index page after successful user creation
        else
            render :new, status: :unprocessable_entity
            # Render the new template if validation fails
        end
    end

    private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end 

    def set_user
        @user = User.find(params[:id])
        # Find the user by ID for actions that require a specific user
    end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div>
    <%= form_with(model: @user) do |form| %>

        <% if @user.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
                <ul>
                    <% @user.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <div>
            <%= form.label :email %>
            <%= form.email_field :email, required: true %>
        </div>

        <div>
            <%= form.label :password %>
            <%= form.password_field :password, required: true %>
        </div>

         <div>
            <%= form.label :password_confirmation %>
            <%= form.password_field :password_confirmation, required: true %>
        </div>

        <div>
            <%= form.submit buttonText %>
        </div>
    <% end %>
</div>

app/views/users/_user.html.erb
<div>
    <%= profile.name %> <br>
    <%= profile.user.email %>
    <%= link_to 'View Profile', profile_path(profile) %>
</div>

app/views/users/edit.html.erb
 <h1>Edit User Profile</h1>

<%= render 'form', buttonText: 'Edit Profile'  %>

app/views/users/index.html.erb
<h1>Users</h1>


<div>
    <% @users.each do |user| %>
      <%= render 'user', profile: user.profile %>
    <% end %>   
</div>

app/views/users/new.html.erb
<h1> Sign up </h1>

<%= render 'form', buttonText: ' Sign up' %>

app/views/users/show.html.erb
<h1> Users </h1>    

<div>
   <%= @user.email %> <br>
   <%= link_to 'Edit Profile', edit_user_path(@user) %> <br>
   <%= button_to 'Delete Account', user_destroy_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %>
   <br>
</div>