config/routes.rb
Rails.application.routes.draw do
  resources :maquillajes
  resources :comments, except: %i[index new show]
  resources :categories
  resources :profiles

  get '/maquillajes', to: 'maquillajes#index'

  get '/confirm_email/:token', to: 'users#confirm_email'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  delete '/user/:id', to: 'users#destroy', as: 'user_destroy'

  post '/login', to: 'sessions#create', as: 'create_session'
  get '/login', to: 'sessions#login', as: 'login'

  get '/user/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/user/:id', to: 'users#update', as: 'update_user'
  get '/user/:id', to: 'users#show', as: 'user'
  get '/users', to: 'users#index'
  
  get '/signup', to: 'users#new', as: 'signup'
  post '/users', to: 'users#create', as: 'create_user'


  patch '/articles/:id', to: 'articles#update', as: 'update_article'
  post '/articles', to: 'articles#create'
  delete '/articles/:id', to: 'articles#destroy', as: 'article_destroy'
  get '/articles', to: 'articles#index'
  get '/articles/new', to: 'articles#new'
  get '/articles/:id', to: 'articles#show', as: 'article'
  get '/articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :name, presence: true, length: { maximum: 100 }
    validates :description, presence: true
    has_one_attached :avatar 
    has_rich_text :body
    has_and_belongs_to_many :categories
    has_many :comments , dependent: :destroy
    # Ensure that both name and description are present
    belongs_to :user

end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
    has_and_belongs_to_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/maquillaje.rb
class Maquillaje < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :name, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :birth, presence: true
  validates :gender, presence: true
  validate :validate_gender

  belongs_to :user

  enum role: [:member, :admin, :superadmin]
  after_create :set_role

  private
  def validate_gender
    if self.gender =! 'Male' || self.gender =! 'Female'
      errors.add(:gender, "was not included in the list")
    end
  end

  def set_role
    self.update(role: 0) if self.role.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_token :token, length: 50
    validates :email, presence: true
    validates :password, presence: true, length: { minimum: 6 }, if: :password_present?
    validates :password_confirmation, length: { minimum: 6 }, if: :password_present?
    has_secure_password # This adds methods to set and authenticate against a BCrypt password.
    has_many :articles, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_one :profile, dependent: :destroy

    private

    def password_present?
        false || password.present?
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def index
        @articles = Article.all
        end
    
    def new 
        @article = Article.new
    end

    def show
    @comment = Comment.new
    end

    def edit
    end

    def update
        if @article.update(article_params)
             redirect_to article_path(@article), notice: "Article was successfully updated."
        else
            render :edit, status: :unprocessable_entity
        end 
    end

    
    def create
        @article = current_user.articles.build(article_params)
        if @article.save
            redirect_to articles_path, notice: "Article was successfully created."
        else
            render :new, status: :unprocessable_entity
        end
    end
    
    def destroy
        @article.destroy
        redirect_to articles_path
    end




    private

    def article_params
        params.require(:article).permit(:name, :description, :avatar, :body, category_ids: [])
    end

  

    def set_article
        @article = Article.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[edit update destroy ]

  def edit
  end

  def create
    @comment = current_user.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_path(@comment.article_id), notice: "Comment was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to article_path(@comment.article_id), status: :see_other, notice: "Comment was successfully destroyed." }
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:text, :article_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @num = 1
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authenticate_user!, only: [:new, :create, :confirm_email]
    before_action :set_user, only: %i[show edit update destroy] 
    
    def index
        @users = User.all
        # Fetch all users to display in the index view
    end

    def show
    end
    
    def new
        @user = User.new
        # Initialize a new user object for the signup form
    end

    def edit
        # This action is used to render the edit user form
        # The @user instance variable is set by the before_action :set_user
    end

    def update
        if @user.update(user_params)
            redirect_to user_path(@user), notice: "User was successfully updated."
            # Redirect to the user's show page after successful update
        else
            render :edit, status: :unprocessable_entity
            # Render the edit template if validation fails
        end
    end

    def destroy
    
        session[:user_id] = nil if current_user == @user
        @user.destroy
        redirect_to users_path, notice: "User was successfully deleted."
        # Redirect to the users index page after successful deletion
    end

    def confirm_email
        user = User.find_by(token: params[:token])
        user.update!(is_confirmed?: true)
        redirect_to login_path, notice: "Your email has been confirmed. Please log in."
    end

    # This action handles user signup
    # It creates a new user and logs them in if successful


    def create
        @user = User.new(user_params)
        if @user.save
            UserMailer.with(user: @user).confirm_account.deliver_later
            redirect_to login_path, notice: "An email was sent to your account to confirm your email address."
            # Redirect to the articles index page after successful user creation
        else
            render :new, status: :unprocessable_entity
            # Render the new template if validation fails
        end
    end

    private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end 

    def set_user
        @user = User.find(params[:id])
        # Find the user by ID for actions that require a specific user
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/maquillajes_helper.rb
module MaquillajesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TempApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application.tailwind", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= yield :head %>
  </head>

  <body>
   <%= render "shared/header" %> 
   <%= notice if notice %>
   <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<div>
 <%= form_with model: @article do |form| %>

        <% if @article.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
                <ul>
                    <% @article.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
     <div>
            <%= form.label :name, 'Insert name: ' %>
            <%= form.text_field :name %>
     </div>
        
     <div>
            <%= form.label :description, 'Insert description: ' %>
            <%= form.text_field :description %>  
    </div>

        
    <div>
            <%= form.submit  %>
    </div>

     <% end %>
</div>

app/views/shared/_header.html.erb
<nav class="flex justify-between p-3 bg-blue-900">
      <ul class="flex gap-2 items-center">
        <li class= "font-bold text-lg text-white"> <%= link_to 'Rails App', root_path %></li>
        <% if current_user && current_user.profile.present? %>
        <li> <%= link_to 'Articles', articles_path, class: "px-4 py-2 bg-red-500 text-white text-sm font-semibold rounded" %> </li>
        <li> <%= link_to 'Users', users_path, class: "test-btn" %> </li> 
        <li> <%= link_to 'Categories', categories_path %> </li>
        <li> <%= link_to 'New Article', articles_new_path %> </li>
        <li> <%= link_to 'Maquillajes', maquillaje_path(current_user.profile) %> </li>
        
        <% end %>
      </ul>

      <ul class="flex gap-2 items-center">
        <% if current_user %>
        <li> <%= button_to 'Logout', logout_path, method: :delete %></li>
        <li> <%= current_user.email %> </li>
        
      <% else %>
        <li> <%= link_to 'Login', login_path %></li>
        <li> <%= link_to 'Sign Up', signup_path %></li>
        <% end %>
      </ul>
</nav>  