config/routes.rb
Rails.application.routes.draw do
  resources :maquillajes
  resources :comments, except: %i[index new show]
  resources :categories
  resources :profiles

  get '/maquillajes', to: 'maquillajes#index'

  get '/confirm_email/:token', to: 'users#confirm_email'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  delete '/user/:id', to: 'users#destroy', as: 'user_destroy'

  post '/login', to: 'sessions#create', as: 'create_session'
  get '/login', to: 'sessions#login', as: 'login'

  get '/user/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/user/:id', to: 'users#update', as: 'update_user'
  get '/user/:id', to: 'users#show', as: 'user'
  get '/users', to: 'users#index'
  
  get '/signup', to: 'users#new', as: 'signup'
  post '/users', to: 'users#create', as: 'create_user'


  patch '/articles/:id', to: 'articles#update', as: 'update_article'
  post '/articles', to: 'articles#create'
  delete '/articles/:id', to: 'articles#destroy', as: 'article_destroy'
  get '/articles', to: 'articles#index'
  get '/articles/new', to: 'articles#new'
  get '/articles/:id', to: 'articles#show', as: 'article'
  get '/articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "pages#home"
end

app/models/maquillaje.rb
class Maquillaje < ApplicationRecord
end

app/controllers/maquillajes_controller.rb
class MaquillajesController < ApplicationController
  before_action :set_maquillaje, only: %i[ show edit update destroy ]

  # GET /maquillajes or /maquillajes.json
  def index
    @maquillajes = Maquillaje.all
  end

  # GET /maquillajes/1 or /maquillajes/1.json
  def show
  end

  # GET /maquillajes/new
  def new
    @maquillaje = Maquillaje.new
  end

  # GET /maquillajes/1/edit
  def edit
  end

  # POST /maquillajes or /maquillajes.json
  def create
    @maquillaje = Maquillaje.new(maquillaje_params)

    respond_to do |format|
      if @maquillaje.save
        format.html { redirect_to @maquillaje, notice: "Maquillaje was successfully created." }
        format.json { render :show, status: :created, location: @maquillaje }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @maquillaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maquillajes/1 or /maquillajes/1.json
  def update
    respond_to do |format|
      if @maquillaje.update(maquillaje_params)
        format.html { redirect_to @maquillaje, notice: "Maquillaje was successfully updated." }
        format.json { render :show, status: :ok, location: @maquillaje }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @maquillaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maquillajes/1 or /maquillajes/1.json
  def destroy
    @maquillaje.destroy!

    respond_to do |format|
      format.html { redirect_to maquillajes_path, status: :see_other, notice: "Maquillaje was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maquillaje
      @maquillaje = Maquillaje.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maquillaje_params
      params.require(:maquillaje).permit(:name, :description, :price)
    end
end

app/helpers/maquillajes_helper.rb
module MaquillajesHelper
end

app/views/maquillajes/_form.html.erb
<%= form_with(model: maquillaje, class: "contents") do |form| %>
  <% if maquillaje.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(maquillaje.errors.count, "error") %> prohibited this maquillaje from being saved:</h2>

      <ul class="list-disc ml-6">
        <% maquillaje.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": maquillaje.errors[:name].none?, "border-red-400 focus:outline-red-600": maquillaje.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": maquillaje.errors[:description].none?, "border-red-400 focus:outline-red-600": maquillaje.errors[:description].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.number_field :price, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": maquillaje.errors[:price].none?, "border-red-400 focus:outline-red-600": maquillaje.errors[:price].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/maquillajes/_maquillaje.html.erb
<div id="<%= dom_id maquillaje %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= maquillaje.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Description:</strong>
    <%= maquillaje.description %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Price:</strong>
    <%= maquillaje.price %>
  </div>
</div>

app/views/maquillajes/edit.html.erb
<% content_for :title, "Editing maquillaje" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing maquillaje</h1>

  <%= render "form", maquillaje: @maquillaje %>

  <%= link_to "Show this maquillaje", @maquillaje, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to maquillajes", maquillajes_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/maquillajes/index.html.erb
<% content_for :title, "Maquillajes" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Maquillajes</h1>
    <%= link_to "New maquillaje", new_maquillaje_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="maquillajes" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @maquillajes.any? %>
      <% @maquillajes.each do |maquillaje| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render maquillaje %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", maquillaje, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_maquillaje_path(maquillaje), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", maquillaje, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">Aca Toy.</p>
    <% end %>
  </div>
</div>

app/views/maquillajes/new.html.erb
<% content_for :title, "New maquillaje" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New maquillaje</h1>

  <%= render "form", maquillaje: @maquillaje %>

  <%= link_to "Back to maquillajes", maquillajes_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/maquillajes/show.html.erb
<% content_for :title, "Showing maquillaje" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing maquillaje</h1>

  <%= render @maquillaje %>

  <%= link_to "Edit this maquillaje", edit_maquillaje_path(@maquillaje), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to maquillajes", maquillajes_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this maquillaje", @maquillaje, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>